### ISSUE TITLE
computation cost is wrong

### ISSUE THREAD

**Issue by Xiaohong-Deng** [udacity/CarND-Object-Detection-Lab#4]
Instead of Df * Df * M * N * Dk * Dk, it should be Dg * Dg * M * N * Dk * Dk with Dg replacing Df.

Same applies to depthwise and pointwise convolution.

**Comment by mvirgo** [comment]
Ended up having a decently long discussion with another Udacian on why this is the case :)

Using Df is actually following the notation used in the paper - check out section 3.1 in the [MobileNets paper](https://arxiv.org/pdf/1704.04861.pdf), for instance. Per the paper, this is actually because they note they assume the output and input dimensions are equal (which is done with stride of 1 and padding). However, if this assumption isn't given, it looks like your computation would be correct.

We've now updated this in the notebook as such!
